#!/bin/sh
#
# Pre-push hook script that ensures mypy checks, style checks, and tests pass

vagrant ssh -c ". activate \
    && echo 'Checking mypy type annotations...' && mypy . \
    && echo 'Checking if Black would reformat any code...' && black --check . \
    && echo -n 'Running tests: ' && pytest -q \
    && echo 'Checking SCSS style...' && npm run --silent lint:scss \
    && echo 'Checking JS style...' && npm run --silent lint:js \
    && echo 'Checking Python style fully (takes a while)...' && prospector -M"
