#!/bin/sh
#
# Pre-push hook script that ensures mypy checks, style checks, and tests pass

vagrant ssh -c ". activate \
    && echo 'Checking mypy type annotations...' && mypy . \
    && echo -n 'Running tests: ' && pytest -q \
    && echo 'Checking code style (takes a while)...' && pylama"
