---
- name: Add shortener config file
  template:
    src: tildes-shortener.conf.jinja2
    dest: /etc/nginx/sites-available/tildes-shortener.conf
    owner: root
    group: root
    mode: 0644

- name: Enable shortener in nginx
  file:
    path: /etc/nginx/sites-enabled/tildes-shortener.conf
    src: /etc/nginx/sites-available/tildes-shortener.conf
    state: link
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload nginx

- name: Add static sites config file
  template:
    src: tildes-static-sites.conf.jinja2
    dest: /etc/nginx/sites-available/tildes-static-sites.conf
    owner: root
    group: root
    mode: 0644

- name: Enable static sites in nginx
  file:
    path: /etc/nginx/sites-enabled/tildes-static-sites.conf
    src: /etc/nginx/sites-available/tildes-static-sites.conf
    state: link
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload nginx
